export const BASE_URL = 'https://api.themoviedb.org/3';
export const KEY = 'api_key=34aace01c22833500b5a31ff5ef2542a';
export const PARAM_FILMS_DAY = '/trending/movie/day?';
export const PARAM_SEARCH_MOVIE = '/search/movie?';
export const IMG_URL = 'https://image.tmdb.org/t/p/w500';
export const MOVIE = '/movie/';
export const PARAMS_CREDITS = '/credits?';
export const PARAMS_REVIEWS = '/reviews?';
export const PARAMS_LANGUAGE = '&language=en-US';